/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionRouteImport } from './routes/_app/transaction'
import { Route as AppNudgesRouteImport } from './routes/_app/nudges'
import { Route as AppInsightRouteImport } from './routes/_app/insight'
import { Route as AppGrowthRouteImport } from './routes/_app/growth'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInsightCategoryRouteImport } from './routes/_app/insight.$category'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionRoute = AppTransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => AppRoute,
} as any)
const AppNudgesRoute = AppNudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightRoute = AppInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightCategoryRoute = AppInsightCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AppInsightRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/growth': typeof AppGrowthRoute
  '/insight': typeof AppInsightRouteWithChildren
  '/nudges': typeof AppNudgesRoute
  '/transaction': typeof AppTransactionRoute
  '/insight/$category': typeof AppInsightCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/growth': typeof AppGrowthRoute
  '/insight': typeof AppInsightRouteWithChildren
  '/nudges': typeof AppNudgesRoute
  '/transaction': typeof AppTransactionRoute
  '/insight/$category': typeof AppInsightCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/insight': typeof AppInsightRouteWithChildren
  '/_app/nudges': typeof AppNudgesRoute
  '/_app/transaction': typeof AppTransactionRoute
  '/_app/insight/$category': typeof AppInsightCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/growth'
    | '/insight'
    | '/nudges'
    | '/transaction'
    | '/insight/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/growth'
    | '/insight'
    | '/nudges'
    | '/transaction'
    | '/insight/$category'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/growth'
    | '/_app/insight'
    | '/_app/nudges'
    | '/_app/transaction'
    | '/_app/insight/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transaction': {
      id: '/_app/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof AppTransactionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nudges': {
      id: '/_app/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof AppNudgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insight': {
      id: '/_app/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof AppInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insight/$category': {
      id: '/_app/insight/$category'
      path: '/$category'
      fullPath: '/insight/$category'
      preLoaderRoute: typeof AppInsightCategoryRouteImport
      parentRoute: typeof AppInsightRoute
    }
  }
}

interface AppInsightRouteChildren {
  AppInsightCategoryRoute: typeof AppInsightCategoryRoute
}

const AppInsightRouteChildren: AppInsightRouteChildren = {
  AppInsightCategoryRoute: AppInsightCategoryRoute,
}

const AppInsightRouteWithChildren = AppInsightRoute._addFileChildren(
  AppInsightRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppInsightRoute: typeof AppInsightRouteWithChildren
  AppNudgesRoute: typeof AppNudgesRoute
  AppTransactionRoute: typeof AppTransactionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppInsightRoute: AppInsightRouteWithChildren,
  AppNudgesRoute: AppNudgesRoute,
  AppTransactionRoute: AppTransactionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
